### PR TITLE
Augment readme with other demos

### PR DESCRIPTION
**Pull request by paulirish**
This repo is the number 1 search result for service worker demos. And so I want to make sure people looking for that can find some good ones. I've tossed the ones I could find at the top of the readme.  

Seems good? 

cc @jakearchibald @slightlyoff

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Thanks @paulirish. Sorry we are not making much progress on this - still waiting for implementations to support cache API.

**Comment by jakearchibald** [comment]
Excellent stuff.

Btw, the cache polyfill at https://github.com/coonsta/cache-polyfill is good to go. It's what trained-to-thrill uses.

**Comment by marcoscaceres** [comment]
Ah, nice! Will try to find some time to take it for a spin.

**Comment by marcoscaceres** [comment]
Will use it here: https://github.com/w3c-webmob/w3c-webmob-website/issues/26 

For http://www.w3.org/Mobile/IG/

**Pull request merged**
